dreamhunter2333/cloudflare_temp_email

- CHANGELOG.md
- smtp_proxy_server/server.py
- vitepress-docs/docs/zh/guide/feature/send-mail-api.md
- worker/src/send_mail_api.js
- worker/src/utils.js
> feat: add /external/api/send_mail for body verify

- .github/workflows/frontend_pagefunction_deploy.yaml
- worker/src/admin_api/cleanup_api.ts
- worker/src/common.ts
1. Add new workflow action, `Deploy Frontend with page function`
2. Fix a cleanup bug. It throw error when cleanDays is 0
> Add new workflow action and Fix cleanup bug

- CHANGELOG.md
- frontend/src/views/Header.vue
- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- worker/src/commom_api.ts
- worker/src/types.d.ts
- worker/wrangler.toml.template
#368
___
___
- Added `SHOW_GITHUB` configuration to control the visibility of the GitHub link in the frontend.
- Updated the settings API to include the `showGithub` parameter.
- Documented the new `SHOW_GITHUB` configuration in both English and Chinese documentation.
- Updated the changelog to reflect the addition of the `SHOW_GITHUB` configuration.
___
<tr>
<td>
<details>
<summary><strong>Header.vue</strong><dd><code>Add conditional visibility for GitHub menu option</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
frontend/src/views/Header.vue
- Added `showGithub` condition to GitHub menu …
> feat: add SHOW_GITHUB config

- CHANGELOG.md
- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- vitepress-docs/docs/zh/guide/feature/admin.md
- worker/src/types.d.ts
- worker/src/worker.ts
- worker/wrangler.toml.template
#374
___
___
- Added `DISABLE_ADMIN_PASSWORD_CHECK` to the `Bindings` type definition.
- Implemented `DISABLE_ADMIN_PASSWORD_CHECK` in the admin authentication middleware to allow bypassing admin password checks.
- Documented the `DISABLE_ADMIN_PASSWORD_CHECK` configuration option in both English and Chinese CLI documentation.
- Updated the wrangler configuration template to include the `DISABLE_ADMIN_PASSWORD_CHECK` option.
___
<tr>
<td>
<details>
<summary><strong>types.d.ts</strong><dd><code>Add `DISABLE_ADMIN_PASSWORD_CHECK` to Bindings type</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> feat: add DISABLE_ADMIN_PASSWORD_CHECK

- CHANGELOG.md
- frontend/src/store/index.js
- frontend/src/views/common/Login.vue
- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- worker/src/commom_api.ts
- worker/src/common.ts
- worker/src/types.d.ts
- worker/wrangler.toml.template
___
- Added dynamic email validation using a configurable regex pattern in both frontend and backend.
- Updated various components and API responses to include and utilize the new `ADDRESS_REGEX` configuration.
- Enhanced documentation to reflect the new `ADDRESS_REGEX` configuration option.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>5 files</summary><table>
<tr>
<td>
<details>
<summary><strong>Login.vue</strong><dd><code>Add dynamic email validation using regex</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
frontend/src/views/common/Login.vue
<li>Added …
> feat: add ADDRESS_REGEX

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/api/index.js
- frontend/src/store/index.js
- vitepress-docs/docs/zh/guide/quick-start.md
- vitepress-docs/docs/zh/guide/ui/worker.md
- worker/package.json
- worker/pnpm-lock.yaml
- worker/src/commom_api.ts
#390
___
Bug fix, Enhancement, Documentation
___
- Added `disableAdminPasswordCheck` to the settings response in the backend.
- Updated global state and admin page visibility logic in the frontend to consider `disableAdminPasswordCheck`.
- Added error handling for missing domains in the settings response.
- Updated several frontend and worker dependencies to their latest versions.
- Added a new section for the upgrade process in the documentation.
- Added a note about string format for variables in the documentation.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>2 files</summary><table>
<tr>
<td>
<details>
<summary><strong>commom_api.ts</strong><dd><code>Add `disableAdminPasswordCheck` …
> fix: DISABLE_ADMIN_PASSWORD_CHECK still show admin password modal

- CHANGELOG.md
- frontend/src/views/Admin.vue
- frontend/src/views/admin/Account.vue
Bug fix, Documentation
___
- Reordered the user ID fetch logic in `Admin.vue` to ensure it is executed before checking the `showAdminPage` condition.
- Removed the unused `showAdminAuth` import in `Account.vue`.
- Updated `CHANGELOG.md` to include an entry for the admin page password prompt fix.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>Admin.vue</strong><dd><code>Fix user ID fetch logic in Admin page</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
frontend/src/views/Admin.vue
<li>Reordered the user ID fetch logic to ensure it is executed …
> fix: UI admin page show modal when no need password

- CHANGELOG.md
- frontend/src/views/Admin.vue
- frontend/src/views/admin/WorkerConfig.vue
- worker/src/admin_api/index.ts
- worker/src/admin_api/worker_config.ts
Enhancement
___
- Added a new `WorkerConfig` component to the Admin view, including its integration into the UI with new tabs for quick setup and maintenance.
- Created a new `WorkerConfig` Vue component that fetches and displays worker configuration data.
- Introduced a new API endpoint in the backend to fetch worker configuration settings.
- Implemented a new module in the backend to handle the worker configuration API logic.
___
<tr>
<td>
<details>
<summary><strong>Admin.vue</strong><dd><code>Add WorkerConfig component and integrate into Admin view</code>&nbsp; </dd></summary>
<hr>
frontend/src/views/Admin.vue
<li>Added import for …
> feat: UI: add WorkerConfig && release v0.7.3

- CHANGELOG.md
- worker/src/common.ts
- worker/src/utils.ts
#430 
#431
___
Bug fix, Enhancement
___
- Enhanced name validation by adding a block list check in the `newAddress` function.
- Fixed handling of `DEFAULT_DOMAINS` configuration to ensure proper fallback when it is undefined or null.
- Updated the changelog to reflect the latest changes and fixes in version 0.7.4.
___
<tr>
<td>
<details>
<summary><strong>common.ts</strong><dd><code>Enhance name validation and add block list check</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
worker/src/common.ts
<li>Added <code>checkNameBlockList</code> function to validate names against a block <br>list.<br> <li> Modified …
> fix: bugs && release v0.7.4

- CHANGELOG.md
- frontend/package.json
- pages/package.json
- vitepress-docs/package.json
- worker/package.json
- worker/src/common.ts
- worker/src/constants.ts
> fix: name check bug

- frontend/src/views/Index.vue
- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- worker/src/admin_api/mail_webhook_settings.ts
- worker/src/common.ts
- worker/src/email/index.ts
- worker/src/mails_api/index.ts
- worker/src/mails_api/webhook_settings.ts
- worker/src/models/index.ts
- worker/src/types.d.ts
- worker/wrangler.toml.template
#429
___
___
- Added functionality to query mails by ID in the mailbox view.
- Enhanced webhook payload to include mail ID and URL.
- Added new API endpoint to fetch mail by ID.
- Updated documentation to include `FRONTEND_URL` configuration.
- Modified SQL queries to fetch mail ID along with raw email.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td>
<details>
<summary><strong>Index.vue</strong><dd><code>Add mail ID query functionality in the mailbox view</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
frontend/src/views/Index.vue
<li>Added <code>useRoute</code> to handle route changes.<br> <li> Introduced …
> feat: add mail id and url in webhook

- CHANGELOG.md
- frontend/src/views/admin/UserOauth2Settings.vue
- vitepress-docs/docs/zh/guide/ui/worker.md
enhancement, documentation
___
- Added 'Delete' button and functionality for OAuth2 settings in the admin portal.
- Implemented confirmation pop-up for delete action.
- Updated localization strings for the new 'Delete' button in both English and Chinese.
- Updated changelog to include the new OAuth2 delete feature.
- Enhanced worker guide documentation with additional compatibility flag details.
___
<tr>
<td>
<details>
<summary><strong>UserOauth2Settings.vue</strong><dd><code>Add delete functionality for OAuth2 settings in admin portal</code></dd></summary>
<hr>
frontend/src/views/admin/UserOauth2Settings.vue
<li>Added 'Delete' button to UI for OAuth2 …
> feat: |UI| admin portal user oauth config support delete

- CHANGELOG.md
- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- worker/src/admin_api/worker_config.ts
- worker/src/email/check_junk.ts
- worker/src/types.d.ts
- worker/wrangler.toml.template
#531
___
enhancement, documentation
___
- Added `JUNK_MAIL_FORCE_PASS_LIST` to the admin API configuration to allow specifying mandatory checks for junk mail.
- Implemented logic in `check_junk.ts` to validate emails against the `JUNK_MAIL_FORCE_PASS_LIST`.
- Updated `Bindings` type definition to include `JUNK_MAIL_FORCE_PASS_LIST`.
- Documented the new configuration option in both English and Chinese CLI guides.
- Added an example configuration for `JUNK_MAIL_FORCE_PASS_LIST` in the wrangler template.
___
<tr>
<td>
<details>
<summary><strong>worker_config.ts</strong><dd><code>Add `JUNK_MAIL_FORCE_PASS_LIST` to admin API …
> feat: |UI| add JUNK_MAIL_FORCE_PASS_LIST

- CHANGELOG.md
- frontend/package.json
- frontend/src/views/admin/MailsUnknow.vue
- pages/package.json
- vitepress-docs/package.json
- worker/package.json
- worker/src/constants.ts
bug fix
___
- Corrected API endpoint for deleting mails in admin view
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>MailsUnknow.vue</strong><dd><code>Correct API endpoint for deleting mails</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
frontend/src/views/admin/MailsUnknow.vue
<li>Fixed the API endpoint for deleting mails from <code>/api/mails/</code> to <br><code>/admin/mails/</code>
</details>
</td>
<td><a href="https://github.com/dreamhunter2333/cloudflare_temp_email/pull/542/files#diff-3ff95e089e16c427acbb2adee5316571377a0eb1034d6dac9ae312259733d8d0">+1/-1< …
> fix: |UI| admin mails unknown page call wrong api

- CHANGELOG.md
- worker/src/telegram_api/common.ts
- worker/src/telegram_api/telegram.ts
enhancement
___
- Add new Telegram bot command to clean invalid JWTs.
- Update `jwtListToAddressData` function to return invalid JWTs.
- Modify Telegram bot commands list to include the new command.
- Update CHANGELOG.md to reflect the new feature.
___
<tr>
<td>
<details>
<summary><strong>common.ts</strong><dd><code>Enhance `jwtListToAddressData` to handle invalid JWTs</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
worker/src/telegram_api/common.ts
<li>Update <code>jwtListToAddressData</code> to return invalid JWTs.<br> <li> Add handling for invalid JWTs in the address list.
</details>
</td>
<td><a …
> feat: |Telegram Bot| add new command to clean invalid jwts

- worker/src/common.ts
- worker/src/email/index.ts
- worker/src/telegram_api/telegram.ts
- worker/src/types.d.ts
- parsedEmailContext在commonParseMail解析后设置了parsedEmail（否则仍然会重复解析）
- 请求头使用objectc传递（用 Map<string,string> 及 Header类，在JSON.stringify后会是{}）
- 修改telegram.ts中的typo
--------------------
不使用parsedEmail中的headers主要是解析后和原样不一致，例如Message-ID，原本<xxx>，解析后parsedEmail变成xxx，无法保持原数据
> fix: rpc headers covert & typo

- frontend/src/views/telegram/Mail.vue
bug fix, enhancement
___
- Replace `div` with `iframe` to display email content.
- Improve email rendering in Telegram mail page.
___
<tr>
<td>
<details>
<summary><strong>Mail.vue</strong><dd><code>Use iframe for email content rendering</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
frontend/src/views/telegram/Mail.vue
<li>Replace <code>div</code> with <code>iframe</code> for email content.<br> <li> Adjust iframe dimensions for better display.
</details>
</td>
<td><a href="https://github.com/dreamhunter2333/cloudflare_temp_email/pull/561/files#d …
> fix: telegram mail page use iframe show email

- CHANGELOG.md
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/App.vue
- frontend/src/api/index.js
- frontend/src/views/Header.vue
- frontend/src/views/common/About.vue
- frontend/src/views/common/Login.vue
- frontend/vite.config.js
- pages/package.json
- scripts/update-dependencies.sh
- vitepress-docs/docs/.vitepress/zh.ts
- vitepress-docs/docs/zh/guide/common-issues.md
- vitepress-docs/package.json
- vitepress-docs/pnpm-lock.yaml
- worker/package.json
- worker/pnpm-lock.yaml
- worker/src/constants.ts
#565
___
Enhancement
___
- Added HTML support for announcements.
- Integrated `useNotification` for displaying announcements.
- Updated `getOpenSettings` to use notifications.
- Modified UI components to display announcements.
___
<tr>
<td>
<details>
<summary><strong>App.vue</strong><dd><code>Add notification provider for HTML announcements</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
frontend/src/App.vue
<li>Added <code>n-notification-provider</code> for HTML announcements.<br> <li> Nested <code>n-message-provider</code> within <code>n-notification-provider</code>.
</details>
</td>
<td><a …
> feat: announcement support html

- frontend/src/views/Footer.vue
enhancement
___
- Add HTML support to footer copyright text
- Refactor footer template for better alignment
___
<tr>
<td>
<details>
<summary><strong>Footer.vue</strong><dd><code>Add HTML support and refactor footer alignment</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
frontend/src/views/Footer.vue
<li>Add HTML support for <code>openSettings.copyright</code><br> <li> Refactor footer text into <code>n-space</code> for better alignment
</details>
</td>
<td><a href="https://github.com/dreamhunter2333/cloudflare_temp_email/pull/567/files#diff-1ce43c99ddad2a0b33fd0bc5bc73f10e5754e0a3ab722753762f0e7e542b …
> feat: footer support html

- worker/src/admin_api/worker_config.ts
- worker/src/email/index.ts
- worker/src/types.d.ts
- worker/src/utils.ts
- worker/wrangler.toml.template
[Feature] 基于子域名转发到不同的邮箱中去 https://github.com/dreamhunter2333/cloudflare_temp_email/issues/645
按我自己的理解，进行了源码修改，应 `dreamhunter2333` 要求，重新做了兼容性调整，主要新增了 `SUBDOMAIN_FORWARD_ADDRESS_LIST` 变量，使其同 USER_ROLES 变量语法类似。
`SUBDOMAIN_FORWARD_ADDRESS_LIST` 变量值格式为：
``` json
[{"domains":[""],"forward":"xxx1@xxx.com"},{"domains":["subdomain-1.domain.com","subdomain-2.domain.com"],"forward":"xxx2@xxx.com"}]
```
其中domains的列表值可为空，为空则代表将全局所有邮件转发到指定邮箱，即如果赋值为
```
SUBDOMAIN_FORWARD_ADDRESS_LIST = [{"domains":[""],"forward":"xxx1@xxx.com"}]
```
则与 `FORWARD_ADDRESS_LIST` 效果等同
```
FORWARD_ADDRESS_LIST = ["xxx1@xxx.com"]
```
> feature: 基于子域名转发到不同的邮箱中去 (#645)
