- worker/package.json
- worker/patches/mailparser@3.6.5.patch
- worker/pnpm-lock.yaml
- worker/src/email.js
> feat: support image

- README.md
- README_EN.md
- frontend/.gitignore
- frontend/src/App.vue
- frontend/src/Content.vue
- worker/src/router.js
> feat: add custom address

- README.md
- README_EN.md
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/App.vue
- frontend/src/Content.vue
- frontend/src/main.js
> feat: add i18n

- README.md
- README_EN.md
- frontend/src/Content.vue
- worker/src/router.js
- worker/wrangler.toml.template
> feat: support multi domain

- README.md
- README_EN.md
- frontend/src/App.vue
- frontend/src/api/index.js
- frontend/src/store/index.js
- frontend/src/views/Content.vue
- frontend/src/views/Header.vue
- worker/src/router.js
- worker/src/worker.js
- worker/wrangler.toml.template
> feat: add auth mode and refactor frontend

- frontend/src/api/index.js
- frontend/src/store/index.js
- worker/src/router.js
> fix: do not show auth when input wrong auth code

- frontend/src/views/Header.vue
> feat: make auth modal cannot be close by user

- worker/src/email.js
> fix: try postal-mime when mailparser failed

- README.md
- README_EN.md
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/App.vue
- frontend/src/api/index.js
- frontend/src/main.js
- frontend/src/router/index.js
- frontend/src/store/index.js
- frontend/src/views/Admin.vue
- frontend/src/views/Content.vue
- frontend/src/views/Index.vue
- worker/src/router.js
- worker/src/worker.js
- worker/wrangler.toml.template
> feat: add admin panel

- frontend/src/api/index.js
- frontend/src/views/Admin.vue
- frontend/src/views/Content.vue
- frontend/src/views/Header.vue
- worker/src/router.js
> feat: add admin query emails

- README.md
- README_EN.md
> feat: update readme for explain ADMIN_PASSWORDS

- frontend/src/views/Content.vue
> feat: modify default class

- README.md
- README_EN.md
> feat: add db changes in readme

- README.md
- README_EN.md
- worker/src/email.js
- worker/wrangler.toml.template
> feat: add ENABLE_ATTACHMENT config

- worker/src/router.js
> feat: check account when get settings

- worker/src/worker.js
> fix: RATE_LIMITER not call jwt

- .github/workflows/frontend_deploy.yaml
- frontend/src/views/send/SendMail.vue
> fix: send_balance not update when click sendmail

- .github/workflows/smtp_proxy_server.yml
- smtp_proxy_server/server.py
> fix: smtp_proxy_server hostname && add docker image for linux/arm64

- frontend/src/utils/email-parser.js
> fix: some browser do not support wasm

- frontend/src/components/MailBox.vue
- frontend/src/router/index.js
- frontend/src/store/index.js
- frontend/src/views/Header.vue
- frontend/src/views/Login.vue
- frontend/src/views/User.vue
- frontend/src/views/user/Account.vue
- frontend/src/views/user/AutoReply.vue
> feat: UI: add user page: useIframeShowMail && mailboxSplitSize

- CHANGELOG.md
- frontend/src/components/MailBox.vue
- frontend/src/store/index.js
- frontend/src/utils/email-parser.js
- frontend/src/views/Index.vue
- frontend/src/views/send/SendMail.vue
> feat: UI: MailBox add reply button

- frontend/src/views/admin/AccountSettings.vue
- frontend/src/views/admin/Maintenance.vue
- frontend/src/views/user/AutoReply.vue
- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- worker/src/admin/cleanup_api.js
- worker/src/admin_api.js
- worker/src/common.js
- worker/src/constants.js
- worker/src/router.js
- worker/src/scheduled.js
- worker/src/user/auto_reply.js
- worker/src/user_api.js
- worker/src/utils.js
- worker/src/worker.js
- worker/wrangler.toml.template
> feat: add cron auto clean up

- worker/src/admin_api.js
> fix: admin/delete_address

- frontend/src/components/MailBox.vue
- frontend/src/utils/email-parser.js
> feat: quote content when reply message

- vitepress-docs/docs/.vitepress/zh.ts
- vitepress-docs/docs/zh/guide/feature/mail-api.md
- vitepress-docs/docs/zh/guide/feature/send-mail-api.md
> feat: update docs

- frontend/src/components/Turnstile.vue
- worker/src/common.js
- worker/src/mails_api/send_mail_api.js
> fix: name max 30 && /external/api/send_mail not return result

- smtp_proxy_server/server.py
> fix: smtp_proxy_server support decode from mail charset

- frontend/src/views/Admin.vue
- frontend/src/views/admin/Telegram.vue
- frontend/src/views/common/About.vue
- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- vitepress-docs/docs/zh/guide/feature/config-smtp-proxy.md
- vitepress-docs/docs/zh/guide/feature/mail-api.md
- vitepress-docs/docs/zh/guide/ui/worker.md
- worker/.gitignore
- worker/package.json
- worker/patches/telegraf@4.16.3.patch
- worker/pnpm-lock.yaml
- worker/src/admin_api/index.js
- worker/src/common.js
- worker/src/constants.ts
- worker/src/email.js
- worker/src/mails_api/index.js
- worker/src/telegram_api/index.ts
- worker/src/telegram_api/telegram.ts
- worker/src/utils.js
- worker/src/worker.js
- worker/tsconfig.json
- worker/wrangler.toml.template
> feat: telegram bot

- smtp_proxy_server/imap_server.py
- smtp_proxy_server/smtp_server.py
- worker/src/telegram_api/telegram.ts
> fix: smtp_proxy: cannot decode 8bit && tg bot new random address

- smtp_proxy_server/imap_server.py
- smtp_proxy_server/parse_email.py
- worker/src/mails_api/webhook_settings.ts
> fix: webhook JSON.stringify

- CHANGELOG.md
- frontend/package.json
- worker/src/constants.ts
- worker/src/telegram_api/common.ts
> fix: cannot delete addres when not bind KV

- CHANGELOG.md
- frontend/package.json
- frontend/src/views/index/AddressBar.vue
- frontend/src/views/index/LocalAddress.vue
- vitepress-docs/docs/zh/guide/feature/config-smtp-proxy.md
- vitepress-docs/docs/zh/guide/feature/mail-api.md
- worker/src/constants.ts
> feat: add Local Address Manage

- CHANGELOG.md
- frontend/src/api/index.js
- frontend/src/views/common/Login.vue
- pages/functions/_middleware.js
- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- worker/src/admin_api/index.ts
- worker/src/commom_api.ts
- worker/src/common.ts
- worker/src/types.d.ts
- worker/wrangler.toml.template
> feat: add MIN_ADDRESS_LEN && MAX_ADDRESS_LEN

- .github/workflows/frontend_deploy.yaml
- frontend/package.json
- pages/package.json
> feat: github actions add FRONTEND_BRANCH env

- CHANGELOG.md
- frontend/package.json
- frontend/src/api/index.js
- frontend/src/views/Header.vue
- worker/src/constants.ts
> feat: logo click 5 time to admin page && fix: 401 cannot show auth modal

- db/schema.sql
初始化sql删除创建mails表索引，应该是 2024-07-08 https://github.com/dreamhunter2333/cloudflare_temp_email/commit/80a8848ed88f62b8e282ec54ea55d3784128ce6d 这次提交漏删了
> fix: remove useless sql

- frontend/src/views/common/Login.vue
- worker/src/common.ts
- worker/src/mails_api/index.ts
- worker/src/telegram_api/telegram.ts
> feat: only allow address [a-z0-9]

- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- worker/src/types.d.ts
- worker/src/user_api/user.ts
- worker/wrangler.toml.template
> feat: add USER_DEFAULT_ROLE

- frontend/src/views/admin/Maintenance.vue
- smtp_proxy_server/config.py
- smtp_proxy_server/imap_server.py
> fix: imap proxy do not support password && cleanup days translate

- frontend/src/components/MailBox.vue
- frontend/src/views/telegram/Mail.vue
- vitepress-docs/docs/zh/guide/ui/d1.md
> feat: add loading when process mails

- frontend/src/views/telegram/Mail.vue
Enhancement
___
- Added `loading` state to the `Mail.vue` component to handle loading status during mail processing.
___
<tr>
<td>
<details>
<summary><strong>Mail.vue</strong><dd><code>Add loading state to mail processing view</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
frontend/src/views/telegram/Mail.vue
- Added `loading` state to global state usage.
</details>
</td>
<td><a href="https://github.com/dreamhunter2333/cloudflare_temp_email/pull/367/files#diff-0b8768ec002961fa240a6c2f0ee66bf1f1bddaaa4f85c179cda3985344f5dbd1">+1/-1</a>&nbsp; &nbsp; &nbsp; </td> …
> fix: add loading when process mails

- CHANGELOG.md
- frontend/src/store/index.js
- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- worker/src/commom_api.ts
- worker/src/mails_api/index.ts
- worker/src/mails_api/send_mail_api.ts
- worker/src/types.d.ts
- worker/src/worker.ts
- worker/wrangler.toml.template
#369
___
___
- Added `NO_LIMIT_SEND_ROLE` environment variable to allow specific roles to send emails without balance limits.
- Changed `showGithub` logic to use `DISABLE_SHOW_GITHUB` environment variable.
- Updated middleware to check user role from token for specific API routes.
- Updated type definitions to include new environment variables and user role.
- Updated frontend store to set default GitHub visibility to true.
- Documented new environment variables in both English and Chinese documentation.
- Updated changelog to reflect these changes.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>6 files</summary><table>
<tr>
<td>
<details> …
> feat: add NO_LIMIT_SEND_ROLE

- CHANGELOG.md
- db/2024-08-10-patch.sql
- db/schema.sql
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/views/user/UserLogin.vue
- frontend/src/views/user/UserSettings.vue
- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- worker/package.json
- worker/pnpm-lock.yaml
- worker/src/models/index.ts
- worker/src/user_api/index.ts
- worker/src/user_api/passkey.ts
- worker/src/utils.ts
- worker/src/worker.ts
- worker/wrangler.toml.template
Enhancement, Documentation, Dependencies
___
- Added passkey login functionality to `UserLogin.vue`.
- Added passkey management functionalities (create, rename, delete) to `UserSettings.vue`.
- Implemented passkey API endpoints (get, rename, delete, register, authenticate) in `worker/src/user_api/passkey.ts`.
- Added SQL script to create `user_passkeys` table.
- Updated schema to include `user_passkeys` table.
- Added dependencies for SimpleWebAuthn in `frontend/package.json` and `worker/package.json`.
- Updated lock files to include new dependencies.
- Documented changes related to passkey login and management in `CHANGELOG.md`.
- Corrected typos in Telegram bot configuration in documentation files.
___
<table><thead><tr><th></th><th align="left">Relevant …
> feat: add passkey

- .github/workflows/pr_agent.yml
- CHANGELOG.md
- frontend/src/App.vue
- frontend/src/views/Header.vue
#381 
#391
___
Bug fix, Enhancement
___
- Added an API call to fetch user settings on component mount in `App.vue`, with error handling.
- Optimized the user settings fetch in `Header.vue` by removing redundant API call and adding a conditional check.
- Updated GitHub Actions workflow by removing the `issue_comment` trigger.
- Updated `CHANGELOG.md` to include an entry for version v0.7.1, noting the fix for the user role loading issue.
___
<tr>
<td>
<details>
<summary><strong>App.vue</strong><dd><code>Fetch user settings on component mount with error handling</code></dd></summary>
<hr>
frontend/src/App.vue
<li>Added API call to fetch user settings on …
> fix: get user role before all requests

- CHANGELOG.md
- frontend/package.json
- frontend/src/views/Admin.vue
- frontend/src/views/index/SendMail.vue
- worker/src/constants.ts
#391
___
Bug fix, Enhancement
___
- Added checks to ensure user settings are fetched if `user_id` is not available on both admin and send mail pages.
- Updated worker and frontend package versions to `v0.7.2`.
- Updated CHANGELOG to reflect changes in version `v0.7.2`.
___
<tr>
<td>
<details>
<summary><strong>Admin.vue</strong><dd><code>Ensure user settings are fetched on admin page load</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
frontend/src/views/Admin.vue
<li>Imported <code>api</code> module.<br> <li> Added check to fetch user settings if <code>user_id</code> is not available.<br>
</details>
</td>
<td><a …
> fix: NO_LIMIT_SEND_ROLE when user settings not call

- CHANGELOG.md
- worker/src/user_api/settings.ts
#391
___
Bug fix, Documentation
___
- Fixed the access token generation logic to use the user role directly instead of checking for admin status.
- Updated the changelog to reflect the fix for the `NO_LIMIT_SEND_ROLE` configuration loading issue.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>settings.ts</strong><dd><code>Fix access token generation based on user role</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
worker/src/user_api/settings.ts
<li>Modified the condition to generate an access token based on user role <br>instead of admin status.<br> <li> Ensured <code>user_role</code> is checked directly for …
> fix: NO_LIMIT_SEND_ROLE no access token

- frontend/src/components/MailBox.vue
- frontend/src/components/SendBox.vue
- frontend/src/components/WebhookComponent.vue
- frontend/src/views/Admin.vue
- frontend/src/views/Index.vue
- frontend/src/views/admin/MailWebhook.vue
- frontend/src/views/common/Login.vue
- frontend/src/views/index/SendMail.vue
- vitepress-docs/docs/zh/guide/ui/worker.md
- worker/src/admin_api/index.ts
- worker/src/admin_api/mail_webhook_settings.ts
- worker/src/common.ts
- worker/src/constants.ts
- worker/src/email/index.ts
- worker/src/models/index.ts
#383
___
Enhancement, Tests, Documentation
___
- Added a new Vue component `WebhookComponent` for managing webhook settings, including fetching, saving, and testing functionalities.
- Introduced a new view `MailWebhook` for managing mail webhook settings using the `WebhookComponent`.
- Updated the `Admin.vue` and `Index.vue` views to include new tabs and localization keys for webhook settings.
- Refactored the existing `Webhook.vue` view to use the new `WebhookComponent`.
- Added new API endpoints and handlers for mail webhook settings in the backend.
- Implemented functions to send and trigger webhooks, integrating both admin and user mail webhook settings.
- Fixed a typo in the function call for triggering webhooks in the email processing module.
- Updated the documentation to include …
> feat: update webhook to support global webhook

- CHANGELOG.md
- frontend/package.json
- pages/package.json
- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- vitepress-docs/package.json
- worker/package.json
- worker/src/admin_api/index.ts
- worker/src/common.ts
- worker/src/constants.ts
- worker/src/mails_api/index.ts
- worker/src/telegram_api/common.ts
- worker/src/types.d.ts
- worker/wrangler.toml.template
#414
___
___
- Refactored `newAddress` function calls across multiple files to use an object for parameters.
- Added `checkNameRegex` function to validate address names against `ADDRESS_CHECK_REGEX`.
- Updated `Bindings` type to include `ADDRESS_CHECK_REGEX`.
- Added `/user_api/oauth2` to the list of paths that bypass middleware.
- Updated documentation to include information about the new `ADDRESS_CHECK_REGEX` feature.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>6 files</summary><table>
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Refactor `newAddress` function call to use object parameters</code></dd></summary>
<hr> …
> feat: add ADDRESS_CHECK_REGEX

- CHANGELOG.md
- frontend/src/api/index.js
- frontend/src/store/index.js
- frontend/src/views/admin/UserSettings.vue
- frontend/src/views/admin/Webhook.vue
- frontend/src/views/common/Login.vue
- frontend/src/views/user/UserLogin.vue
- worker/src/admin_api/mail_webhook_settings.ts
- worker/src/mails_api/webhook_settings.ts
- worker/src/worker.ts
Bug fix, Enhancement
___
- Added conditional rendering for input fields in `UserSettings.vue` based on checkbox states.
- Introduced `webhookEnabled` state and conditional rendering in `Webhook.vue`.
- Added conditional rendering for tabs in `Login.vue` and `UserLogin.vue` based on settings fetched status.
- Removed checks for KV availability and webhook enablement in `mail_webhook_settings.ts` and `webhook_settings.ts`.
- Updated middleware in `worker.ts` to include `/admin/mail_webhook` path.
- Ensured settings fetched flag is set in `getOpenSettings` and `getUserOpenSettings` functions.
- Added `fetched` flag to `openSettings` and `userOpenSettings` states in the store.
- Updated changelog to include UI tab active icon position fix.
___
<table><thead><tr><th></th><th …
> fix: UI tab active icon wrong position

- CHANGELOG.md
- frontend/package.json
- pages/package.json
- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- vitepress-docs/package.json
- worker/package.json
- worker/src/constants.ts
- worker/src/telegram_api/telegram.ts
- worker/src/types.d.ts
- worker/src/utils.ts
- worker/wrangler.toml.template
#441
___
___
- Added retrieval of `botInfo` from environment variable `TG_BOT_INFO` and set `bot.botInfo` if available to reduce latency.
- Introduced `getJsonObjectValue` utility function to parse JSON values.
- Updated `Bindings` type to include `TG_BOT_INFO`.
- Documented new `TG_BOT_INFO` environment variable in both English and Chinese documentation.
- Updated changelog to reflect the new feature for setting bot info.
___
<tr>
<td>
<details>
<summary><strong>telegram.ts</strong><dd><code>Set Telegram bot info from environment variable to reduce latency</code></dd></summary>
<hr>
worker/src/telegram_api/telegram.ts
<li>Added …
> feat: telegram Set manually to avoid implicit  call in  or

- frontend/package.json
- frontend/pnpm-lock.yaml
- pages/package.json
- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- worker/package.json
- worker/pnpm-lock.yaml
- worker/wrangler.toml.template
enhancement, documentation
___
- Upgraded multiple dependencies across frontend, worker, and pages packages to their latest versions.
- Updated `compatibility_date` and added `compatibility_flags` in worker configuration examples in both English and Chinese documentation.
- Modified worker configuration template to reflect new compatibility settings.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Upgrade frontend dependencies to latest versions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
frontend/package.json
<li>Upgraded multiple dependencies to newer versions.<br> <li> Updated …
> feat: upgrade dependencies

- .github/workflows/tag_build.yml
- CHANGELOG.md
- frontend/package.json
- frontend/pnpm-lock.yaml
- pages/package.json
- vitepress-docs/package.json
- vitepress-docs/pnpm-lock.yaml
- worker/package.json
- worker/pnpm-lock.yaml
- worker/src/worker.ts
Enhancement, Tests, Dependencies
___
- Added checks for `DB` and `JWT_SECRET` environment variables in the worker middleware.
- Upgraded multiple dependencies in frontend, worker, documentation, and pages.
- Added CI steps to build and zip the Telegram frontend.
- Updated changelog to include Telegram mini app build zip package.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>1 files</summary><table>
<tr>
<td>
<details>
<summary><strong>worker.ts</strong><dd><code>Add environment variable checks in worker middleware</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
worker/src/worker.ts
<li>Added checks for <code>DB</code> and <code>JWT_SECRET</code> environment variables.<br> …
> feat: upgrade dependencies && add ci build telegram-frontend.zip

- CHANGELOG.md
- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- worker/src/admin_api/worker_config.ts
- worker/src/common.ts
- worker/src/email/check_junk.ts
- worker/src/email/index.ts
- worker/src/types.d.ts
- worker/wrangler.toml.template
#435
___
___
- Added `ENABLE_CHECK_JUNK_MAIL` configuration option to enable or disable junk mail checking.
- Implemented a function `check_if_junk_mail` to determine if an email is junk based on SPF, DKIM, and DMARC headers.
- Integrated junk mail checking into the email processing workflow.
- Updated the `Bindings` type to include the `ENABLE_CHECK_JUNK_MAIL` option.
- Documented the new configuration option in both English and Chinese CLI guides.
- Updated the configuration template to include the new option.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>6 files</summary><table>
<tr>
<td>
<details>
<summary><strong>worker_config.ts</strong><dd><code>Add …
> feat: add ENABLE_CHECK_JUNK_MAIL

- frontend/package.json
- frontend/src/main.js
- frontend/vite.config.js
- vitepress-docs/docs/zh/guide/cli/pages.md
#465
___
___
- Added a condition in `frontend/src/main.js` to disable PWA registration based on the `VITE_PWA_DISABLED` environment variable.
- Modified the PWA registration type in `frontend/vite.config.js` to be conditional based on the `VITE_PWA_DISABLED` environment variable.
- Added a new script `build:pages:nopwa` in `frontend/package.json` to build pages without PWA.
- Updated documentation in `vitepress-docs/docs/zh/guide/cli/pages.md` to include instructions for building pages without PWA for Cloudflare Zero Trust.
___
<tr>
<td>
<details>
<summary><strong>main.js</strong><dd><code>Conditional PWA registration based on …
> feat: pages support Cloudflare Zero Trust

- frontend/src/views/user/AddressManagement.vue
- frontend/vite.config.js
Enhancement, Configuration changes
___
- Removed the 'ID' column from the user address management table to enhance UI/UX.
- Disabled the PWA dev options in the Vite configuration to prevent unnecessary service worker registration during development.
___
<tr>
<td>
<details>
<summary><strong>AddressManagement.vue</strong><dd><code>Hide user ID column in Address Management view</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
frontend/src/views/user/AddressManagement.vue
- Removed the 'ID' column from the user address management table.
</details>
</td>
<td><a …
> feat: |UI| hide ID for user

- CHANGELOG.md
- vitepress-docs/docs/zh/guide/config-send-mail.md
- vitepress-docs/docs/zh/guide/email-routing.md
- vitepress-docs/docs/zh/guide/feature/telegram.md
Documentation
___
- Added a breaking changes section in `CHANGELOG.md` with instructions for modifying Compatibility flags for UI deployment worker.
- Updated `config-send-mail.md` to include instructions for adding `RESEND_TOKEN` to secrets and provided alternative methods.
- Clarified steps in `email-routing.md` for configuring email DNS records, enabling email routing, and setting catch-all addresses.
- Updated `telegram.md` to include instructions for adding `TELEGRAM_BOT_TOKEN` to secrets and provided alternative methods.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>CHANGELOG.md</strong><dd><code>Add breaking changes and instructions for UI deployment …
> feat: |doc| update doc

- .github/workflows/frontend_deploy.yaml
enhancement, configuration changes
___
- Enhanced the GitHub Actions workflow for frontend deployment by adding the `--branch` argument to the `pnpm run deploy:actions` and `pnpm run deploy:actions:telegram` commands.
- This change allows specifying the branch to be deployed, improving deployment flexibility.
___
<tr>
<td>
<details>
<summary><strong>frontend_deploy.yaml</strong><dd><code>Add branch argument to deployment commands in GitHub Actions workflow</code></dd></summary>
<hr>
.github/workflows/frontend_deploy.yaml
<li>Added <code>--branch</code> argument to <code>pnpm run deploy:actions</code> command.<br> <li> Added <code>--branch</code> argument …
> fix: frontend github actions cannot use branch param to deploy

- CHANGELOG.md
- frontend/src/views/Admin.vue
- frontend/src/views/admin/SendMail.vue
- worker/src/admin_api/index.ts
- worker/src/admin_api/send_mail.ts
- worker/src/mails_api/send_mail_api.ts
- worker/src/user_api/oauth2.ts
- worker/src/user_api/passkey.ts
- worker/src/user_api/user.ts
#523
___
Enhancement, Bug fix
___
- Added `SendMail` component to the admin portal for sending emails.
- Implemented new API endpoint `/admin/send_mail` for sending emails by admin without balance limit.
- Updated `sendMail` function to support admin email sending.
- Extended JWT expiration from 30 to 90 days in multiple user APIs.
- Updated changelog with recent changes and fixes.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td>
<details>
<summary><strong>Admin.vue</strong><dd><code>Add `SendMail` tab and localization in Admin view</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
frontend/src/views/Admin.vue
<li>Imported …
> feat: support send mail from admin portal(no balance limit)

- CHANGELOG.md
- frontend/src/views/admin/AccountSettings.vue
- worker/src/admin_api/index.ts
- worker/src/constants.ts
- worker/src/mails_api/send_mail_api.ts
___
- Added `noLimitSendAddressList` to the admin account settings page.
- Updated the UI to include a new input field for `noLimitSendAddressList`.
- Modified the fetch and save functions to handle `noLimitSendAddressList`.
- Included `noLimitSendAddressList` in account settings API responses.
- Added `NO_LIMIT_SEND_ADDRESS_LIST_KEY` constant.
- Added logic to check `noLimitSendAddressList` when sending emails.
- Updated balance check conditions to include `noLimitSendAddressList`.
- Updated changelog to include the addition of `noLimitSendAddressList` feature.
___
<tr>
<td>
<details> …
> feat: add NO_LIMIT_SEND_ADDRESS_LIST_KEY in admin account settings page

- CHANGELOG.md
- vitepress-docs/docs/en/cli.md
- vitepress-docs/docs/zh/guide/cli/worker.md
- worker/src/admin_api/mail_webhook_settings.ts
- worker/src/admin_api/worker_config.ts
- worker/src/common.ts
- worker/src/email/check_junk.ts
- worker/src/email/index.ts
- worker/src/mails_api/webhook_settings.ts
- worker/src/telegram_api/telegram.ts
- worker/src/types.d.ts
- worker/wrangler.toml.template
enhancement, bug fix
___
- Introduced `ParsedEmailContext` to cache parsed email content.
- Added `JUNK_MAIL_CHECK_LIST` for conditional junk mail checks.
- Updated functions to use `ParsedEmailContext` instead of raw email strings.
- Enhanced error handling in email processing functions.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td><strong>mail_webhook_settings.ts</strong><dd><code>Use `ParsedEmailContext` in testWebhookSettings</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a href="https://github.com/dreamhunter2333/cloudflare_temp_email/pull/553/files#diff-a8888cea638671df084f06f14c82a84294903585f3a2181618 …
> feat: add JUNK_MAIL_CHECK_LIST for check exits and passed item && add ParsedEmailContext to cache the parsed Email

- CHANGELOG.md
- vitepress-docs/docs/zh/guide/feature/telegram.md
documentation
___
- Fixed a typo in the `CHANGELOG.md` file.
- Added a trial link for the Telegram Bot in the documentation.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>CHANGELOG.md</strong><dd><code>Fixed typo in `JUNK_MAIL_CHECK_LIST` description</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
CHANGELOG.md
<li>Fixed a typo in the <code>JUNK_MAIL_CHECK_LIST</code> configuration description.
</details>
</td>
<td><a href="https://github.com/dreamhunter2333/cloudflare_temp_email/pull/557/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
<tr>
<td> …
> feat: update doc

- .github/config/mail-parser-wasm-worker.patch
- worker/src/common.ts
Bug fix
___
- Fix caching issue in `parsedEmailContext` for mail-parser-wasm.
- Ensure `parsedEmailContext.parsedEmail` is correctly assigned.
- Update patch file for `mail-parser-wasm-worker`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>common.ts</strong><dd><code>Fix parsedEmailContext cache assignment</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
worker/src/common.ts
<li>Fix assignment of <code>parsedEmailContext.parsedEmail</code>.<br> <li> Ensure correct return of <code>parsedEmailContext.parsedEmail</code>.
</details>
</td>
<td><a …
> fix: mail-parser-wasm parsedEmailContext cache
